### ISSUE TITLE
exception events.js:183 on Mac 10.13

### ISSUE THREAD

**Issue by it214test15** [cristijora/vue-light-bootstrap-dashboard#16]
Getting an exception while doing "run dev". No errors during build process.

npm run dev
> node build/dev-server.js

> Starting dev server...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.listen (/Users/sergueijoukov/devl/vue_work/vue-light-bootstrap-dashboard/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/sergueijoukov/devl/vue_work/vue-light-bootstrap-dashboard/build/dev-server.js:85:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by it214test15** [comment]
Never mind. ADDRINUSE :::8000 Duh.
